### ISSUE TITLE
SPS problem

### ISSUE THREAD

**Issue by boromyr** [adienakhmad/ADS1256#6]
Hi, I am writing for a problem encountered in using this library for my ADS1256 with Arduino Uno. The setting for the SPS does not work correctly, I don't know if it is my mistake or a bug, but I have already redone the connections 3 times, and confirmed the operation with other libraries.
Even writing the value in the register does not respond correctly to the settings (`adc.writeRegister (DRATE, ADS1256_DRATE_10SPS);`). The values ​​obtained either remain fixed at 50SPS, or oscillate between 2000 and 3000, or are lower than the set value over 50%.
Below is the code I use to measure SPS over a period of time, working with other ADCs. Furthermore, the gain only seems to divide the result by it's value.

`int count = 0;
    double sum = 0;
    unsigned long t0 = millis();`

    while (millis() - t0 < 1000) {
        adc.setChannel(0, -1);
        float y = adc.readCurrentChannel();
        sum += y;
        count++;
    }

    Serial.print(sum / count, 4);
    Serial.print(" , SPS = ");
    Serial.println(count);`

Arduino UNO,ADS1256 on breadboard,Visual Studio 2019
Thanks.
I apologize for the translator, I don't have much experience with English.

**Comment by chepo92** [comment]
Please post whole code to replicate the problem, but I can guess you are not waiting for the dataReady pin to be set, so you are just reading whatever garbage is in the mux, at a speed as fast as it can read/write. Please refer first to the examples provided to make your code. 

Yes readCurrentChannel PGA uses a scaling by 2*Vref/PGA (so it returns Volts units), will make this more datailed. Page 16 http://www.ti.com/lit/ds/symlink/ads1256.pdf

**Comment by chepo92** [comment]
Made some modifications so yo can get Volts or ADC raw values, see my fork or lastests  PRs #10 and #11

**Comment by boromyr** [comment]
I started using the examples, I thinned out the code by removing the other channels I don't use.

void setup(){
  adc.begin(ADS1256_DRATE_5SPS,ADS1256_GAIN_1,false); 
  Serial.println("ADC Started");
 
}
void loop()
{ 
  adc.waitDRDY(); 
  adc.setChannel(0,-1);  
  sensor1 = adc.readCurrentChannelVolt(); 
  Serial.println(sensor1,10);
  delay(500);
}

Without the delay, it continues to give incorrect and very fast values, with the delay I get the real value (3.3V from Arduino). Using readRegister (DRATE) I get the correct value (19 in this case), but by measuring the actual SPS I get 3000 and more. I connected the Reset pin to fixed 3.3V. I can't find any logic between these results.

**Comment by chepo92** [comment]
Do you use a breakout board? which (link/image)? 
just guessing, I think it's something with DRDY signal, there are some breakoutboards that map out not(DRDY) signal instead of DRDY
I don't currently have the sensor with me, probably could retrieve next week. Can you measure the DRDY period with something like this?

void setup() {
adc.begin(ADS1256_DRATE_5SPS,ADS1256_GAIN_1,false);
Serial.println("ADC Started");
adc.setChannel(0,-1);
}
void loop()
{
adc.waitDRDY();
Serial.println(millis());
}

**Comment by chepo92** [comment]
Ok, think I got some ideas, according to the datasheet, conversion cycle is indicated with a falling edge of DRDY, and stays low until data is read or new cycle is started so waitDRDY() is exiting during all that low period, please use the new function isDRDY() that added yesterday, to check previous and current state of DRDY instead of waitDRDY();

**Comment by boromyr** [comment]
I bought the original cip directly, soldered on PCB and mounted on the breadboard, I completed the connections with jumper cables, oscillator etc. The day before yesterday I managed to obtain the correct values ​​for the SPS set, while yesterday I did not.
 At this point I have to disconnect all things and redo the connections from the beginning, in order to exclude some errors in the connections that inevitably with jumpers on breadboards can happen.
The strange thing is that in any case using other codes the connections work. Possible compatibility problem with non-pre-built boards?

I thank you for your support, as soon as I can I will make new tests and communicate the results in case others may have my problem.

**Comment by adienakhmad** [comment]
One thing you can check is to connect DRDY line to oscilloscope and check it's frequencies. Does it match with the given DRATE?

Do you use 7.68Mhz as the CLK_IN?

**Comment by boromyr** [comment]
8Mhz, I used the spreadsheet and Excel to check the new SPS values ​​and they deviate slightly (e.g. from 25 to 25.8 approximately). I don't have an oscilloscope, although there are several codes for Arduino and STM32. But I could calculate the frequency using the chepo92 code [adc.waitDRDY ();
Serial.println (millis ()); ] if my intuition is correct, should it match the value of DRATE?

**Comment by adienakhmad** [comment]
> But I could calculate the frequency using the chepo92 code [adc.waitDRDY ();
Serial.println (millis ()); ] if my intuition is correct, should it match the value of DRATE?

I'm not sure but from a quick glance it seems like it won't work, because `waitDRDY()` will finish immediately while the `DRDY` signal is low. It will only be back high again when the data is read. Plus it would be the period of data being available to read, not `DRATE`. 

The correct approach to infer `DRATE` from `DRDY` signal is to measure the period when it is HIGH ( settling time). You can then calculate `DRATE = 1.0 / settling_time`

I remember doing SPS test, I can no longer find the script I used back then, the result was the DRATE matches until it reached 7500SPS (lower when you're cycling between input).

I think the script looks something like this.

```C++
int count = 0;
unsigned long t0 = millis();

adc.setChannel(0);
while (millis() - t0 < 1000) {
    adc.waitDRDY();
    float y = adc.readCurrentChannel();
    count++;
}

Serial.println(count);
```

**Comment by boromyr** [comment]
That's right, it's the same one I use. As I said, I managed to get the correct count with this script, but the next day, I didn't. In all of this the log reading tests were correct.
I will start again as soon as I have time, checking every single step.
Thanks to you both for the support.

**Comment by chepo92** [comment]
this code may be useful to test SPS (use dev branch for the isDRDY function)

```
bool prevDRDY, currentDRDY;

void setup() {
    adc.begin(ADS1256_DRATE_5SPS,ADS1256_GAIN_1,false);
    Serial.println("ADC Started");
    adc.setChannel(0);
    prevDRDY  = adc.isDRDY();
}
void loop() {
    currentDRDY  = adc.isDRDY();
    if (prevDRDY != currentDRDY && currentDRDY==0) {
         Serial.println(millis());
    }
    prevDRDY  = currentDRDY ; 
}
```

**Comment by boromyr** [comment]
So, I managed to solve the problem: redo all the connections from scratch, fixed the vRef and the capacitors, deleted the library and reinstalled. Probably some connection problems, which unfortunately always happen with jumpers. I thank you immensely for your help and dedicated time !!!!! THANK YOU!!!!

@chepo92 
Regarding your last code, I am not getting a reply in the serial. The library did not contain the isDRDY () function in the .h file, but only in the .cpp file, I had to enter the function manually. Version 6 instead has the opposite problem.

**Comment by chepo92** [comment]
> 
> @chepo92
> Regarding your last code, I am not getting a reply in the serial. The library did not contain the isDRDY () function in the .h file, but only in the .cpp file, I had to enter the function manually. Version 6 instead has the opposite problem.


Thanks, now should be fixed
